menu:
  Home: /
  Archives: /archives

# gitment
gitment: false
gitment_owner:
gitment_repo:
gitment_client_id:
gitment_client_secret:

# gitalk
gitalk: false
gitalk_owner:
gitalk_admin: []
gitalk_repo:
gitalk_client_id:
gitalk_client_secret:

# valine comment
valine: false
leancloud_id:
leancloud_key:

# disqus comment
disqus: false
disqus_shortname:

# google analytics
googleTrackId:

# whether to show read more button when showing article in excerpt in main page
read_more: false

# whether to use a dynamic avatar or just show a static one
# max_distance and sensitivity only work when dynamic_avatar is true
dynamic_avatar: true
max_distance: 15
sensitivity: 0.01
